(library
 (name datagen)
 (modules datagen)
 (libraries owl)
)


(test
 (name test_datagen)
 (modules test_datagen)
 (libraries alcotest datagen)
)

(test
	(name test_analysis)
	(modules test_analysis)
	(libraries data alcotest datagen)
	(action (run %{test} --show-errors))
)

(test
	(name test_rng)
	(modules test_rng)
	(libraries testu01 owl)
)
