open Alcotest.V1
open Datagen
open Owl

(* TODO: could also test skewness, kurtosis, 0 for normal? but not for all rand... *)

(**
    Even a perfect random number generator is expected to fail randomness tests sometimes,
    because the randomness test is only accurate up to (1-alpha)*100% accuracy.
    And we cannot make alpha 0 or it would never reject bad sequences either.

    So instead we perform several trials, and only consider a hypothesis failed if it got rejected 4 times in a row.
    This should result in a much smaller (but still non-zero!) chance of false positives from this test
    (in essence 0.05^4)
*)
let evaluate_hypothesis ~alpha hypothesis generator =
    let test () = (generator () |> hypothesis ~alpha).Stats.reject in
    test () && test () && test () && test ()

(** [test_hypothesis ?xfail ?trials msg generator hypothesis] tests the [hypothesis] on data generated by [generate].

    @param xfail whether the hypothesis is expected to be rejected
    @param msg error message to show if the hypothesis is not rejected/accepted as expected
*)
let test_hypothesis ?(alpha = 0.05) ?(xfail = false) msg hypothesis generator =
    test_case msg `Quick @@ fun () ->
    let reject = evaluate_hypothesis ~alpha hypothesis generator in
    if xfail != reject then
        failf "%s: hypothesis (reject = %b) (xfail = %b)" msg reject xfail

(** Uniform random tests *)

let test_mean ?(expected=0.5) ~abserr f () =
    let data = f () in
    check' ~msg:"mean" ~expected ~actual:(Stats.mean data) (float abserr)

let test_median ?(expected=0.5) ~abserr f () =
    let data = f () in
    check' ~msg:"median" ~expected ~actual:(Stats.median data) (float abserr)

let is_random_order ~alpha data = Stats.runs_test ~alpha data

let is_uniform_random ~alpha data = Stats.ks_test ~alpha data @@ Stats.uniform_cdf ~a:0. ~b:1.

let test_range ~lo ~hi f () =
    f () |> Array.iter @@ fun v ->
    if v <= lo || v >= hi then
        failf "data out of (0,1) range: %g" v

let n_0_1 x = Stats.gaussian_cdf x ~mu:0. ~sigma:1.

let turning_points data =
    data |> Array.to_seqi |> Seq.fold_left (fun t (i, x) ->
        if i = 0 || i+1 = Array.length data then t
        else
        let x0, x1, x2 = data.(i-1), x, data.(i+1) in
        let is_monotonic =
           (x0 <= x1 && x1 <= x2) ||
           (x0 >= x1 && x1 >= x2)
        in
        if is_monotonic then t
        else t+1 (* this is a turning point *)
    ) 0

let is_iid ~alpha data =
    (* Le Boudec, Jean-Yves. Performance Evaluation of Computer and Communication Systems, 2010 *)
    let t = turning_points data |> float_of_int in
    let n = float_of_int (Array.length data) in
    let mu = (2. *. n -. 4.) /. 3. in
    let var = (16. *. n -. 29.) /. 90. in
    let p_value = 2. *. (1. -. n_0_1 ((t -. mu) /. sqrt var)) in
    Stats.{ reject = alpha > p_value
    ; p_value
    ; score = t
    }

let test_uniform ?(abserr=Float.epsilon) ?(random=true) f n =
    let f () = f n in
    let always =
        [ test_hypothesis "uniform" is_uniform_random f
        ; test_case "range" `Quick (test_range ~lo:0. ~hi:1.0 f)
        ]
    in
    let always =
        if random then
            (* cannot use xfail, because not all non-random sources fail this test *)
            test_hypothesis "iid" is_iid f :: always
        else
            always
    in
    if n > 100 then
        (* these ones need a lot of data points to be accurate,
           have to use confidence intervals otherwise (but that is done in test_analysis)
         *)
        test_hypothesis "random order" ~xfail:(not random) is_random_order f
        :: test_case "mean" `Quick (test_mean ~abserr f)
        :: test_case "median" `Quick (test_median ~abserr f)
        :: always
    else
        always

(** Normal tests *)

let is_normal_random ~mu ~sigma ~alpha data =
    Stats.ks_test ~alpha data @@ Stats.gaussian_cdf ~mu ~sigma

let test_normal_range ~mu ~sigma =
    (* the probability that a normal value would be outside of this range is very very low *)
    let m = Owl.Stats.gaussian_isf ~mu ~sigma Float.epsilon in
    let lo = mu -. sigma *. m
    and hi = mu +. sigma *. m in
    test_range ~lo ~hi

let is_variance ~sigma ~alpha data = Stats.var_test ~alpha ~variance:(sigma *. sigma) data

let is_mean ~mean ~sigma ~alpha data = Stats.z_test ~alpha ~mu:mean ~sigma data

let is_normal ~alpha data = Stats.jb_test ~alpha data

let test_normal ?(random=true) f ~mu ~sigma n =
    let f () = f ~mu ~sigma n in
    let always =
        [ test_hypothesis "normal (JB)" is_normal f
            ; test_hypothesis "normal with known mu&sigma" (is_normal_random ~mu ~sigma) f
            ; test_case "range" `Quick (test_normal_range ~mu ~sigma f)
            ; test_hypothesis "normal mean test" (is_mean ~mean:mu ~sigma) f
            ; test_hypothesis "variance test" (is_variance ~sigma) f
        ]
    in
    let always =
        if random then
            (* cannot use xfail, because not all non-random sources fail this test *)
            test_hypothesis "iid" is_iid f :: always
        else
            always
    in
    if (n >= 100) then
        (* these need a lot of datapoints to be accurate *)
        test_hypothesis "random order" ~xfail:(not random) is_random_order f
        :: always
    else
        always

(** All tests *)

let () =
    let tests =
        [1000; 100; 5; 3;]
        |> List.concat_map (fun n ->
        [ "Uniform.rand", test_uniform ~abserr:0.1 Uniform.rand n
        ; "Uniform.linspace", test_uniform ~random:false Uniform.linspace n
        ; "Uniform.low_discrepancy", test_uniform ~abserr:0.001 ~random:false Uniform.low_discrepancy n
        ; "Normal.rand1", test_normal Normal.rand1 ~mu:0. ~sigma:1.0 n
        ; "Normal.rand2", test_normal Normal.rand2 ~mu:0. ~sigma:1.0 n
        ; "Normal.fixed", test_normal ~random:false Normal.fixed ~mu:0. ~sigma:1.0 n
        ; "Normal.low_discrepancy", test_normal ~random:false Normal.low_discrepancy ~mu:0. ~sigma:1.0 n
        ; "Normal.rand1 (2)", test_normal Normal.rand1 ~mu:10. ~sigma:2.0 n
        ; "Normal.rand2 (2)", test_normal Normal.rand2 ~mu:10. ~sigma:2.0 n
        ; "Normal.fixed (2)", test_normal ~random:false Normal.fixed ~mu:10. ~sigma:2. n
        ; "Normal.low_discrepancy (2)", test_normal ~random:false Normal.low_discrepancy ~mu:10. ~sigma:2. n
        ]
        |> List.map @@ fun (name, t) ->
                Printf.sprintf "%s (%d)" name n, t
        )
    in 
    run "random" tests
