(library
 (name data)
 (libraries unix owl-base owl)
 (wrapped false)
 (preprocess
  (pps ppx_sexp_conv ppx_let))
 (modules analysis))

(executable
 (public_name rage)
 (name main)
 (modules :standard \ analysis)
 (flags
  (:standard -principal -short-paths))
 (preprocess
  (pps ppx_sexp_conv ppx_let))
 (libraries data threads.posix core postgresql curl async sql uri str re ssl owl-base owl ezjsonm unix))
